name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # options
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bahia
          plugin_achievements: yes
          plugin_notable: yes
          plugin_licenses: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_lines: yes
          plugin_languages_ignored: >-
            html, css, tex, less, makefile, qmake, lex, shell,
            gnuplot, javascript
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar_duration: full-year
