name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # options
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bahia
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_projects: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, javascript
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage
          plugin_isocalendar_duration: full-year
